site_name: Ramifice Docs
site_description: "ORM-pseudo-like API MongoDB for Python language."
site_url: https://kebasyaty.github.io/ramifice/
site_author: kebasyaty
copyright: Copyright &copy; 2025 Maintained by <a href="https://github.com/kebasyaty">kebasyaty</a>
repo_name: kebasyaty/ramifice
repo_url: https://github.com/kebasyaty/ramifice

theme:
  name: material
  language: en
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

extra_css:
  - stylesheets/themes/github_indigo.css
  - stylesheets/extra.css

plugins:
  - search
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  version:
    provider: mike
    default: latest
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kebasyaty
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com

nav:
  - Ramifice: index.md
  - Installation: pages/installation/index.md
  - Usage:
      - Usage: pages/usage/index.md
      - Create Model: pages/usage/create_model.md
      - Model Parameters: pages/usage/model_parameters.md
      - Class Methods: pages/usage/class_methods.md
      - Instance Methods: pages/usage/instance_methods.md
      - Utils: pages/usage/utils.md
  - Localization: pages/localization/index.md
  - Models:
      - Models: pages/models/index.md
      - Model: pages/models/model.md
      - Decorator: pages/models/decorator.md
  - Fields:
      - Fields: pages/fields/index.md
      - TextField: pages/fields/text_field.md
      - EmailField: pages/fields/email_field.md
      - PhoneField: pages/fields/phone_field.md
      - PasswordField: pages/fields/password_field.md
      - ImageField: pages/fields/image_field.md
      - FileField: pages/fields/file_field.md
      - DateField: pages/fields/date_field.md
      - DateTimeField: pages/fields/date_time_field.md
      - IntegerField: pages/fields/integer_field.md
      - FloatField: pages/fields/float_field.md
      - BooleanField: pages/fields/bool_field.md
      - IPField: pages/fields/ip_field.md
      - URLField: pages/fields/url_field.md
      - ColorField: pages/fields/color_field.md
      - IDField: pages/fields/id_field.md
      - SlugField: pages/fields/slug_field.md
      - ChoiceFloatDynField: pages/fields/choice_float_dyn_field.md
      - ChoiceFloatField: pages/fields/choice_float_field.md
      - ChoiceFloatMultDynField: pages/fields/choice_float_mult_dyn_field.md
      - ChoiceFloatMultField: pages/fields/choice_float_mult_field.md
      - ChoiceIntDynField: pages/fields/choice_int_dyn_field.md
      - ChoiceIntField: pages/fields/choice_int_field.md
      - ChoiceIntMultDynField: pages/fields/choice_int_mult_dyn_field.md
      - ChoiceIntMultField: pages/fields/choice_int_mult_field.md
      - ChoiceTextDynField: pages/fields/choice_text_dyn_field.md
      - ChoiceTextField: pages/fields/choice_text_field.md
      - ChoiceTextMultDynField: pages/fields/choice_text_mult_dyn_field.md
      - ChoiceTextMultField: pages/fields/choice_text_mult_field.md
  - Paladins:
      - Paladins: pages/paladins/index.md
      - Check: pages/paladins/check.md
      - Save: pages/paladins/save.md
      - Delete: pages/paladins/delete.md
      - Add Validation: pages/paladins/add_valid.md
      - Hooks: pages/paladins/hooks.md
      - Indexing: pages/paladins/indexing.md
      - Password: pages/paladins/password.md
      - Refrash: pages/paladins/refrash.md
      - Validation: pages/paladins/validation.md
      - Tools: pages/paladins/tools.md
  - Commons:
      - Commons: pages/commons/index.md
      - General: pages/commons/general.md
      - Indexes: pages/commons/indexes.md
      - Many: pages/commons/many.md
      - One: pages/commons/one.md
      - Tools: pages/commons/tools.md
      - Unit Manager: pages/commons/unit_manager.md
  - Utils:
      - Utils: pages/utils/index.md
      - Constants: pages/utils/constants.md
      - Errors: pages/utils/errors.md
      - Fixtures: pages/utils/fixtures.md
      - Migration: pages/utils/migration.md
      - Mixins: pages/utils/mixins.md
      - Tools: pages/utils/tools.md
      - Translations: pages/utils/translations.md
      - Unit: pages/utils/unit.md
